navigation:
  - title: Home
    url: /
  - title: About Me
    url: /aboutme/
  - title: Projects
    url: /projects/
  - title: Contact Me
    url: /contactme/
navigation:
  - title: Home
    url: /
  - title: About
    url: /aboutme/
    subnavigation:
      - title: Skills
        url: /skills/
      - title: Experience
        url: /experience/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contactme/
/* Custom Navigation Styles */
.navbar {
  background-color: rgba(0, 0, 0, 0.8); /* Semi-transparent background */
}

.navbar a {
  color: #ffffff !important; /* White text for links */
}

.navbar a:hover {
  color: #1e90ff !important; /* Highlight color on hover */
}
