title: Your Site Title
description: A brief description of your site.
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Resume
    url: /resume/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/

github_username: Ishwar75
linkedin_username: your-linkedin-username
twitter_username: your-twitter-username

# Optional: Google Analytics
google_analytics: UA-XXXXXXXXX-X

# Optional: Social Icons
social_links:
  - icon: fa-github
    url: https://github.com/Ishwar75
  - icon: fa-linkedin
    url: https://www.linkedin.com/in/your-linkedin-username/
  - icon: fa-twitter
    url: https://twitter.com/your-twitter-username
