title: Ishwar Netaam
description: A brief description of your site.
url: "https://ishwarnetam.github.io" # your site URL
baseurl: "" # leave empty for user site

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Author
author:
  name: Ishwar Netaam
  email: your-email@example.com

# Social Links
social:
  - icon: github
    link: https://github.com/ishwar75
  - icon: twitter
    link: https://twitter.com/yourusername
  - icon: linkedin
    link: https://linkedin.com/in/yourusername
  # Add more as needed

# Navigation
navigation:
  - title: Home
    url: /
  - title: About Me
    url: /aboutme
  - title: Contact Me
    url: /contactme
  # Add more as needed

# Optional: Customize other settings as per Minimal Mistakes documentation
