title: Ishwar Netaam
description: A passionate software developer specializing in web development.
url: "https://ishwarnetam.github.io" # your site URL
baseurl: "" # leave empty for user site

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Author
author:
  name: Ishwar Netaam
  email: your-email@example.com

# Social Links
social:
  - icon: github
    link: "https://github.com/ishwar75"
  - icon: twitter
    link: "https://twitter.com/yourusername"
  - icon: linkedin
    link: "https://linkedin.com/in/yourusername"
  # Add more as needed

# Navigation
navigation:
  - title: Home
    url: "/"
  - title: About Me
    url: "/about_me.html"
  - title: Research
    url: "/research.html"
  - title: Contact
    url: "/contact.html"
  # Add more as needed

# SEO Configuration
seo:
  title: "Ishwar Netaam Portfolio"
  description: "A passionate software developer specializing in web development."
  keywords: ["developer", "software", "web development", "portfolio"]
  lang: "en"
  twitter:
    site: "@yourtwitterhandle"
    creator: "@yourtwitterhandle"
  open_graph:
    type: "website"
    locale: "en_US"
    url: "https://ishwarnetam.github.io"
    title: "Ishwar Netaam Portfolio"
    description: "A passionate software developer specializing in web development."
    image: "/assets/images/seo-image.jpg"

# Google Analytics (Optional)
google_analytics: "UA-XXXXXXXXX-X"

# Optional: Customize other settings as per Minimal Mistakes documentation
