title: Ishwar Netam
description: Software Developer | Open Source Enthusiast | Tech Blogger
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ishwarnetam.github.io" # the base hostname & protocol for your site

theme: minima # Remove or replace if using a remote theme

# To use Minimal Mistakes, specify it as a remote theme
remote_theme: mmistakes/minimal-mistakes@4.24.0


plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache


# Navigation links
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Resume
    url: /resume/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/
markdown: kramdown
kramdown:
  input: GFM

# Social links
github_username: Ishwar75
linkedin_username: Ishwarnetam.linkden.in
twitter_username: your-twitter-username
